Grid Tile Styling for previous entries
KidEinstein/sps-team-37 pull request #16
Opened 2020-07-19 19:11 UTC by mariah-crawford

Uses CSS to style the previous entries of the journal to look like mini tiles with pages from a journal

2020-07-20 23:01 UTC, gracieorozco requested changes
Aside from the minor file error, I tested everything else, and it looks great. Once the file is uploaded, I'll verify the branch works once more and approve the changes.

2020-07-20 23:01 UTC, gracieorozco commented on src/main/webapp/style.css
> +    background-image: url("images/linedpaper.jpg");
When I ran this branch, there was an error saying that this file was not found. If you can upload the image file, I believe it should resolve the problem.

2020-07-21 02:58 UTC, mariah-crawford commented on src/main/webapp/style.css
> +    background-image: url("images/linedpaper.jpg");
Thanks for reviewing my pull request! :) I added the image file and committed the change

2020-07-22 01:47 UTC, gracieorozco approved these changes
It works now, thank you for making the changes. Feel free to merge the branch.

2020-07-23 02:22 UTC, merged