Mood Graphs
KidEinstein/sps-team-37 pull request #5
Opened 2020-07-06 05:38 UTC by gracieorozco

The graph contains data retrieved from a GET request to the data servlet. Within the DataServlet.java file, a query is made to retrieve the Journal entities which are then converted to Journal objects. The Journal objects are then placed into an ArrayList of Journal objects to be converted into a JSON format using the Gson library.

2020-07-06 16:10 UTC, dprado981 requested changes
Overall looks pretty good to me. Make sure not to commit anything under the target directory, I don't think it's best practice to commit them. (I should've probably added it to the .gitignore now that I'm thinking about it)

2020-07-06 16:10 UTC, dprado981 commented on src/main/java/com/google/sps/servlets/DataServlet.java
> +
I don't think having this as an instance variable is necessary. I think it would be better if it was just a local variable in the doGet method.

2020-07-06 16:10 UTC, dprado981 commented on src/main/webapp/graphs.html
> +    </style>
Consider moving styling to separate CSS file

2020-07-08 00:25 UTC, gracieorozco commented on src/main/java/com/google/sps/servlets/DataServlet.java
> +
I have updated the placement.

2020-07-08 00:25 UTC, gracieorozco commented on src/main/webapp/graphs.html
> +    </style>
I have moved the code into the CSS file.

2020-07-08 01:25 UTC, gracieorozco commented
Once you approve the pull request, feel free to merge it when you can.

2020-07-08 01:36 UTC, dprado981 approved these changes
Changes look good!

2020-07-08 01:37 UTC, merged